FROM node:20-alpine AS frontend-builder

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./

ARG API_BASE_URL=/api
ARG SOCKET_URL=https://queuely.daw.inspedralbes.cat

ENV API_BASE_URL=${API_BASE_URL}
ENV SOCKET_URL=${SOCKET_URL}

RUN npm run generate

FROM nginx:1.27-alpine

COPY nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /app/frontend/.output/public /usr/share/nginx/html

EXPOSE 80
